---
config:
  theme: neutral
---
flowchart TD
    subgraph US[User Service]
        FriendshipRequest -- from / to --> User
        Profile --> User
    end
    subgraph CS[Chat Service]
        User --send--> Message
    end
    subgraph ES[Engagement Service]
        Profile --create--> Post
        Profile --> Like
        Profile --create--> Comment
        Comment --> Post
        Like --> Comment
        Like --> Post
    end

style US fill: lightblue
style ES fill: #ACE1AF
style CS fill: #DDA0DD